name: Build and Publish Docker Image on Push to Main

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * Sun"
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ORG_NAME: kaakaww
  IMAGE_NAME: owasp-benchmark

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          manifest: true
          platforms: |
            linux/amd64,linux/arm64
          tags: |
            ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          push_tags: |
            ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          manifest_tags: |
            ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Push README to Docker Hub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          repository: ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}
